In [1]:
import requests
import json
import pandas as pd
import numpy as np
from bs4 import BeautifulSoup

In [2]:
#getting url
URL = "https://topforeignstocks.com/indices/the-components-of-the-korea-stock-exchange-kospi-index/"
page = requests.get(URL)
soup = BeautifulSoup(page.content, "html.parser")

In [3]:
print (soup.prettify())

<!DOCTYPE html>
<html lang="en-US" prefix="" xmlns="http://www.w3.org/1999/xhtml">
 <head>
  <!-- Global site tag (gtag.js) - Google Analytics -->
  <script async="" src="https://www.googletagmanager.com/gtag/js?id=UA-129064405-1">
  </script>
  <script>
   window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'UA-129064405-1');
  </script>
  <!-- Global site tag (gtag.js) - Google Analytics -->
  <script async="" src="https://www.googletagmanager.com/gtag/js?id=UA-11539341-1">
  </script>
  <script>
   window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'UA-11539341-1');
  </script>
  <meta charset="utf-8"/>
  <meta content="width=device-width" name="viewport"/>
  <title>
   The Components of the Korea KOSPI Index | TopForeignStocks.com
  </title>
  <link href="https://gmpg.org/xfn/11" rel="profile"/>
  <link href="https://topforeignstocks.com/xmlrpc.php" rel="pingback"/>
  <!--[if lt IE 9]>
<script src="https://topforeignstocks.com/wp-content/themes/f2/js/html5.js" type="text/javascript"></script>
<![endif]-->
  <!-- BEGIN Metadata added by the Add-Meta-Tags WordPress plugin -->
  <meta content="The Components of the Korea Stock Exchange KOSPI Index for 2018 are listed below: Source: KSE Download: The Components of the Korea KOSPI Index for 2018 (in Excel format) Related Links: Realtime KOSPI Quote (Bloomberg) Realtime KOSPI Quote (Yahoo Finance) KOSPI (Wikipedia) Realtime KOSPI Quote(Ko..." name="description"/>
  <!-- END Metadata added by the Add-Meta-Tags WordPress plugin -->
  <link href="//fonts.googleapis.com" rel="dns-prefetch"/>
  <link href="//s.w.org" rel="dns-prefetch"/>
  <link href="https://topforeignstocks.com/feed/" rel="alternate" title="TopForeignStocks.com » Feed" type="application/rss+xml"/>
  <link href="https://topforeignstocks.com/comments/feed/" rel="alternate" title="TopForeignStocks.com » Comments Feed" type="application/rss+xml"/>
  <link href="https://topforeignstocks.com/indices/the-components-of-the-korea-stock-exchange-kospi-index/feed/" rel="alternate" title="TopForeignStocks.com » The Components of the Korea KOSPI Index Comments Feed" type="application/rss+xml"/>
  <script type="text/javascript">
   window._wpemojiSettings = {"baseUrl":"https:\/\/s.w.org\/images\/core\/emoji\/11\/72x72\/","ext":".png","svgUrl":"https:\/\/s.w.org\/images\/core\/emoji\/11\/svg\/","svgExt":".svg","source":{"concatemoji":"https:\/\/topforeignstocks.com\/wp-includes\/js\/wp-emoji-release.min.js?ver=4.9.16"}};
			!function(a,b,c){function d(a,b){var c=String.fromCharCode;l.clearRect(0,0,k.width,k.height),l.fillText(c.apply(this,a),0,0);var d=k.toDataURL();l.clearRect(0,0,k.width,k.height),l.fillText(c.apply(this,b),0,0);var e=k.toDataURL();return d===e}function e(a){var b;if(!l||!l.fillText)return!1;switch(l.textBaseline="top",l.font="600 32px Arial",a){case"flag":return!(b=d([55356,56826,55356,56819],[55356,56826,8203,55356,56819]))&&(b=d([55356,57332,56128,56423,56128,56418,56128,56421,56128,56430,56128,56423,56128,56447],[55356,57332,8203,56128,56423,8203,56128,56418,8203,56128,56421,8203,56128,56430,8203,56128,56423,8203,56128,56447]),!b);case"emoji":return b=d([55358,56760,9792,65039],[55358,56760,8203,9792,65039]),!b}return!1}function f(a){var c=b.createElement("script");c.src=a,c.defer=c.type="text/javascript",b.getElementsByTagName("head")[0].appendChild(c)}var g,h,i,j,k=b.createElement("canvas"),l=k.getContext&&k.getContext("2d");for(j=Array("flag","emoji"),c.supports={everything:!0,everythingExceptFlag:!0},i=0;i<j.length;i++)c.supports[j[i]]=e(j[i]),c.supports.everything=c.supports.everything&&c.supports[j[i]],"flag"!==j[i]&&(c.supports.everythingExceptFlag=c.supports.everythingExceptFlag&&c.supports[j[i]]);c.supports.everythingExceptFlag=c.supports.everythingExceptFlag&&!c.supports.flag,c.DOMReady=!1,c.readyCallback=function(){c.DOMReady=!0},c.supports.everything||(h=function(){c.readyCallback()},b.addEventListener?(b.addEventListener("DOMContentLoaded",h,!1),a.addEventListener("load",h,!1)):(a.attachEvent("onload",h),b.attachEvent("onreadystatechange",function(){"complete"===b.readyState&&c.readyCallback()})),g=c.source||{},g.concatemoji?f(g.concatemoji):g.wpemoji&&g.twemoji&&(f(g.twemoji),f(g.wpemoji)))}(window,document,window._wpemojiSettings);
  </script>
  <style type="text/css">
   img.wp-smiley,
img.emoji {
	display: inline !important;
	border: none !important;
	box-shadow: none !important;
	height: 1em !important;
	width: 1em !important;
	margin: 0 .07em !important;
	vertical-align: -0.1em !important;
	background: none !important;
	padding: 0 !important;
}
  </style>
  <link href="https://topforeignstocks.com/wp-content/cache/minify/1210a.css" media="all" rel="stylesheet"/>
  <link href="https://fonts.googleapis.com/css?family=Bitter:700|Gudea:400,700,400italic" id="webfonts-css" media="all" rel="stylesheet" type="text/css"/>
  <link href="https://topforeignstocks.com/wp-content/cache/minify/643a7.css" media="all" rel="stylesheet"/>
  <link href="https://topforeignstocks.com/wp-content/themes/f2/print.css?ver=0.0.2" id="print-css" media="print" rel="stylesheet" type="text/css"/>
  <!--[if lt IE 9]>
<link rel='stylesheet' id='ie-style-css'  href='https://topforeignstocks.com/wp-content/themes/f2/ie.css?ver=0.0.2' type='text/css' media='screen, projection' />
<![endif]-->
  <!--[if lt IE 8]>
<link rel='stylesheet' id='ie7-style-css'  href='https://topforeignstocks.com/wp-content/themes/f2/ie7.css?ver=0.0.2' type='text/css' media='screen, projection' />
<![endif]-->
  <style id="an_style-inline-css" type="text/css">
   /*	an_style.css	AdBlock Notify	Copyright: (c) 2016 Themeisle, themeisle.com	Version: 2.2.3*/.RyDZtPfPlEmM-bg {	display: none;	position: fixed;	z-index: 100;	top: 0;	left: 0;	width: 100%;	height: 100%;	background: #000;	background: rgba(0,0,0,0.75);}.RyDZtPfPlEmM {	visibility: hidden;	position: fixed;	z-index: 101;	top: 100px;	right: 0;	left: 0;	max-width: 640px;	margin-right: auto;	margin-left: auto;	background: #fff;	-webkit-box-shadow: 0 3px 5px 2px rgba(0,0,0,0.25);	box-shadow: 0 3px 5px 2px rgba(0,0,0,0.25);	font-family: Arial, Helvetica, sans-serif;}.RyDZtPfPlEmM-default,.RyDZtPfPlEmM-ok {	padding: 30px 30px 15px;}.RyDZtPfPlEmM-image {	overflow: hidden;	position: relative;	width: 100%;}.RyDZtPfPlEmM-image .RyDZtPfPlEmM-left {	position: absolute;	top: 0;	left: 0;	width: 50%;	height: 100%;}.RyDZtPfPlEmM-image .RyDZtPfPlEmM-right {	float: right;	width: 50%;	padding: 30px;}.RyDZtPfPlEmM.small {	width: 200px;	margin-left: -140px;}.RyDZtPfPlEmM.medium {	width: 400px;	margin-left: -240px;}.RyDZtPfPlEmM.large {	width: 600px;	margin-left: -340px;}.RyDZtPfPlEmM.xlarge {	width: 800px;	margin-left: -440px;}.close-RyDZtPfPlEmM {	display: inline-block;	position: absolute;	top: 15px;	right: 15px;	width: 30px;	height: 30px;	color: #bbb;	font-size: 32px;	font-weight: 700;	line-height: 30px;	text-align: center;	cursor: pointer;	-webkit-transition: 0.3s;	transition: 0.3s;}.close-RyDZtPfPlEmM:hover {	color: #252b37;}.RyDZtPfPlEmM h1 {	margin-bottom: 15px;	padding: 0 30px;	color: #252b37;	font-size: 28px;	line-height: 1.25;	text-align: center;}.RyDZtPfPlEmM-right h1 {	padding: 0 30px 0 0;	text-align: left;}.RyDZtPfPlEmM p {	margin-bottom: 15px;	color: #333745;	font-size: 14px;}.RyDZtPfPlEmM p a {	color: #ff6160;}.RyDZtPfPlEmM-right .close-modal,.RyDZtPfPlEmM-footer .close-modal {	padding: 15px !important;	border-radius: 0 !important;	background-color: #ff6160;	font-size: 14px;	letter-spacing: 2px !important;	-webkit-transition: 0.3s;	transition: 0.3s;}.RyDZtPfPlEmM-right .close-modal:hover,.RyDZtPfPlEmM-footer .close-modal:hover {	background-color: #252b37 !important;}.RyDZtPfPlEmM-footer .grey-button-modal {	margin-right: 15px;	background-color: #a5a5a5;}.RyDZtPfPlEmM-footer {	display: block;	padding: 15px 30px;	background-color: #eff4f7;	text-align: right;}@media only screen and (max-width: 640px) {	.RyDZtPfPlEmM {		right: 5%;		left: 5%;		max-width: 90%;	}	.RyDZtPfPlEmM-default {		padding: 20px;	}	.RyDZtPfPlEmM-image .RyDZtPfPlEmM-left {		width: 100%;		height: 250px;	}	.RyDZtPfPlEmM-image .RyDZtPfPlEmM-right {		float: left;		width: 100%;		margin-top: 250px;		padding: 20px;	}	.RyDZtPfPlEmM h1 {		margin-bottom: 10px;		font-size: 20px;	}	.RyDZtPfPlEmM-right h1 {		padding: 0;	}	.RyDZtPfPlEmM p {		margin-bottom: 10px;	}	.close-RyDZtPfPlEmM {		color: #fcfcfc;		background-color: #252b37;	}	.close-RyDZtPfPlEmM:hover {		color: #252b37;		background-color: #fcfcfc;	}	.RyDZtPfPlEmM-footer {		padding: 15px 20px;	}}@media only screen and (max-width: 480px) {	.RyDZtPfPlEmM-image .RyDZtPfPlEmM-left {		height: 200px;	}	.RyDZtPfPlEmM-image .RyDZtPfPlEmM-right {		margin-top: 200px;	}	.RyDZtPfPlEmM-footer {		text-align: center;	}	.RyDZtPfPlEmM-footer .close-modal {		width: 80%;		margin: 5px 10%;	}}
  </style>
  <script>
   !(function(o,n,t){t=o.createElement(n),o=o.getElementsByTagName(n)[0],t.async=1,t.src="https://steadfastsystem.com/v2/0/iaehE0ads5ahUPWo3__pzwvCMuHclRwyzc-htimVCF8stNK-tnBtrcP4CugayRZGhxrb90qlxUvbAZPBHra9xO1oSz3LaSHPVwH_cCZwtoV2TuEi8T2lTCRCWdFi93FX72BiH5eig",o.parentNode.insertBefore(t,o)})(document,"script"),(function(o,n){o[n]=o[n]||function(){(o[n].q=o[n].q||[]).push(arguments)}})(window,"admiral");!(function(n,e,r,t){function o(){if((function o(t){try{return(t=localStorage.getItem("v4ac1eiZr0"))&&0<t.split(",")[4]}catch(n){}return!1})()){var t=n[e].pubads();typeof t.setTargeting===r&&t.setTargeting("admiral-engaged","true")}}(t=n[e]=n[e]||{}).cmd=t.cmd||[],typeof t.pubads===r?o():typeof t.cmd.unshift===r?t.cmd.unshift(o):t.cmd.push(o)})(window,"googletag","function");
  </script>
  <script>
   if (document.location.protocol != "https:") {document.location = document.URL.replace(/^http:/i, "https:");}
  </script>
  <script src="https://topforeignstocks.com/wp-content/cache/minify/df983.js">
  </script>
  <link href="https://topforeignstocks.com/wp-json/" rel="https://api.w.org/"/>
  <link href="https://topforeignstocks.com/xmlrpc.php?rsd" rel="EditURI" title="RSD" type="application/rsd+xml"/>
  <link href="https://topforeignstocks.com/wp-includes/wlwmanifest.xml" rel="wlwmanifest" type="application/wlwmanifest+xml"/>
  <meta content="WordPress 4.9.16" name="generator"/>
  <link href="https://topforeignstocks.com/indices/the-components-of-the-korea-stock-exchange-kospi-index/" rel="canonical"/>
  <link href="https://topforeignstocks.com/?p=11581" rel="shortlink"/>
  <link href="https://topforeignstocks.com/wp-json/oembed/1.0/embed?url=https%3A%2F%2Ftopforeignstocks.com%2Findices%2Fthe-components-of-the-korea-stock-exchange-kospi-index%2F" rel="alternate" type="application/json+oembed"/>
  <link href="https://topforeignstocks.com/wp-json/oembed/1.0/embed?url=https%3A%2F%2Ftopforeignstocks.com%2Findices%2Fthe-components-of-the-korea-stock-exchange-kospi-index%2F&amp;format=xml" rel="alternate" type="text/xml+oembed"/>
  <style>
   #related_posts_thumbnails li{
          border-right: 1px solid #dddddd;
          background-color: #ffffff      }
      #related_posts_thumbnails li:hover{
          background-color: #eeeeee;
      }
      .relpost_content{
          font-size: 12px;
          color: #333333;
      }
      .relpost-block-single{
          background-color: #ffffff;
          border-right: 1px solid  #dddddd;
          border-left: 1px solid  #dddddd;
          margin-right: -1px;
      }
      .relpost-block-single:hover{
          background-color: #eeeeee;
      }
  </style>
  <style type="text/css">
   .broken_link, a.broken_link {
	text-decoration: line-through;
}
  </style>
 </head>
 <body class="page-template-default page page-id-11581 page-child parent-pageid-1487 one-sidebar-right wide-sidebar medium-font-sidebar large-font-content" data-rsssl="1">
  <div class="hfeed site" id="page">
   <header class="site-header" id="masthead" role="banner">
    <div id="header-wrap">
     <hgroup>
      <h1 class="site-title">
       <a href="https://topforeignstocks.com/" rel="home" title="TopForeignStocks.com">
        TopForeignStocks.com
       </a>
      </h1>
      <h2 class="site-description">
       Your Money. Your Future.
      </h2>
     </hgroup>
     <script charset="utf-8" src="//ads.investingchannel.com/adtags/topforeignstocks/exchange_traded_fund/728x90.js" type="text/javascript">
     </script>
    </div>
    <nav class="site-navigation main-navigation" role="navigation">
     <h1 class="assistive-text">
      Menu
     </h1>
     <div class="assistive-text skip-link">
      <a href="#content" title="Skip to content">
       Skip to content
      </a>
     </div>
     <div class="menu-main-menu-container">
      <ul class="menu" id="menu-main-menu">
       <li class="menu-item menu-item-type-custom menu-item-object-custom menu-item-home menu-item-15616" id="menu-item-15616">
        <a href="https://topforeignstocks.com/">
         Home
        </a>
       </li>
       <li class="menu-item menu-item-type-post_type menu-item-object-page menu-item-15621" id="menu-item-15621">
        <a href="https://topforeignstocks.com/foreign-adrs-list/">
         Foreign ADRs List
        </a>
       </li>
       <li class="menu-item menu-item-type-post_type menu-item-object-page menu-item-15618" id="menu-item-15618">
        <a href="https://topforeignstocks.com/downloads/">
         Downloads
        </a>
       </li>
       <li class="menu-item menu-item-type-post_type menu-item-object-page current-page-ancestor menu-item-15622" id="menu-item-15622">
        <a href="https://topforeignstocks.com/indices/">
         Indices
        </a>
       </li>
       <li class="menu-item menu-item-type-post_type menu-item-object-page menu-item-15620" id="menu-item-15620">
        <a href="https://topforeignstocks.com/etf-lists/">
         ETF Lists
        </a>
       </li>
       <li class="menu-item menu-item-type-post_type menu-item-object-page menu-item-15617" id="menu-item-15617">
        <a href="https://topforeignstocks.com/about/">
         About Us
        </a>
       </li>
       <li class="menu-item menu-item-type-post_type menu-item-object-page menu-item-15619" id="menu-item-15619">
        <a href="https://topforeignstocks.com/education/">
         Education
        </a>
       </li>
       <li class="menu-item menu-item-type-post_type menu-item-object-page menu-item-15623" id="menu-item-15623">
        <a href="https://topforeignstocks.com/stock-lists/">
         Stock Lists
        </a>
       </li>
       <li class="menu-item menu-item-type-post_type menu-item-object-page menu-item-27005" id="menu-item-27005">
        <a href="https://topforeignstocks.com/dividend-history-us-stocks/">
         Dividend History – US Stocks
        </a>
       </li>
       <li class="menu-item menu-item-type-post_type menu-item-object-page menu-item-38818" id="menu-item-38818">
        <a href="https://topforeignstocks.com/listed-companies-lists/">
         Listed Companies Lists
        </a>
       </li>
      </ul>
     </div>
    </nav>
    <!-- .site-navigation .main-navigation -->
   </header>
   <!-- #masthead .site-header -->
   <div class="site-main" id="main">
    <div class="content-area" id="primary">
     <div class="site-content" id="content" role="main">
      <article class="post-11581 page type-page status-publish hentry" id="post-11581">
       <header class="entry-header">
        <h1 class="entry-title">
         The Components of the Korea KOSPI Index
        </h1>
       </header>
       <!-- .entry-header -->
       <div class="entry-content">
        <p>
         <strong>
          The Components of the Korea Stock Exchange KOSPI Index for 2018 are listed below:
         </strong>
         <br/>
         <table class="tablepress tablepress-id-2054" id="tablepress-2054">
          <thead>
           <tr class="row-1 odd">
            <th class="column-1">
             S.No.
            </th>
            <th class="column-2">
             Name
            </th>
            <th class="column-3">
             Code
            </th>
           </tr>
          </thead>
          <tbody class="row-hover">
           <tr class="row-2 even">
            <td class="column-1">
             1
            </td>
            <td class="column-2">
             A REIT
            </td>
            <td class="column-3">
             140910
            </td>
           </tr>
           <tr class="row-3 odd">
            <td class="column-1">
             2
            </td>
            <td class="column-2">
             A&amp;P
            </td>
            <td class="column-3">
             015260
            </td>
           </tr>
           <tr class="row-4 even">
            <td class="column-1">
             3
            </td>
            <td class="column-2">
             ABLE C&amp;C
            </td>
            <td class="column-3">
             078520
            </td>
           </tr>
           <tr class="row-5 odd">
            <td class="column-1">
             4
            </td>
            <td class="column-2">
             AEKYUNG INDUSTRIAL
            </td>
            <td class="column-3">
             018250
            </td>
           </tr>
           <tr class="row-6 even">
            <td class="column-1">
             5
            </td>
            <td class="column-2">
             AJ Networks
            </td>
            <td class="column-3">
             095570
            </td>
           </tr>
           <tr class="row-7 odd">
            <td class="column-1">
             6
            </td>
            <td class="column-2">
             AJ RENT A CAR
            </td>
            <td class="column-3">
             068400
            </td>
           </tr>
           <tr class="row-8 even">
            <td class="column-1">
             7
            </td>
            <td class="column-2">
             AJU CAPITAL
            </td>
            <td class="column-3">
             033660
            </td>
           </tr>
           <tr class="row-9 odd">
            <td class="column-1">
             8
            </td>
            <td class="column-2">
             AK Holdings
            </td>
            <td class="column-3">
             006840
            </td>
           </tr>
           <tr class="row-10 even">
            <td class="column-1">
             9
            </td>
            <td class="column-2">
             AK Petrochemical
            </td>
            <td class="column-3">
             161000
            </td>
           </tr>
           <tr class="row-11 odd">
            <td class="column-1">
             10
            </td>
            <td class="column-2">
             ALUKO
            </td>
            <td class="column-3">
             001780
            </td>
           </tr>
           <tr class="row-12 even">
            <td class="column-1">
             11
            </td>
            <td class="column-2">
             ALVOGEN KOREA
            </td>
            <td class="column-3">
             002250
            </td>
           </tr>
           <tr class="row-13 odd">
            <td class="column-1">
             12
            </td>
            <td class="column-2">
             AmoreG
            </td>
            <td class="column-3">
             002790
            </td>
           </tr>
           <tr class="row-14 even">
            <td class="column-1">
             13
            </td>
            <td class="column-2">
             AmoreG(1P)
            </td>
            <td class="column-3">
             002795
            </td>
           </tr>
           <tr class="row-15 odd">
            <td class="column-1">
             14
            </td>
            <td class="column-2">
             AMOREPACIFIC
            </td>
            <td class="column-3">
             090430
            </td>
           </tr>

In [4]:
#finding table
table = soup.find("table")
table

<table class="tablepress tablepress-id-2054" id="tablepress-2054">
<thead>
<tr class="row-1 odd">
<th class="column-1">S.No.</th><th class="column-2">Name</th><th class="column-3">Code</th>
</tr>
</thead>
<tbody class="row-hover">
<tr class="row-2 even">
<td class="column-1">1</td><td class="column-2">A REIT</td><td class="column-3">140910</td>
</tr>
<tr class="row-3 odd">
<td class="column-1">2</td><td class="column-2">A&amp;P</td><td class="column-3">015260</td>
</tr>
<tr class="row-4 even">
<td class="column-1">3</td><td class="column-2">ABLE C&amp;C</td><td class="column-3">078520</td>
</tr>
<tr class="row-5 odd">
<td class="column-1">4</td><td class="column-2">AEKYUNG INDUSTRIAL</td><td class="column-3">018250</td>
</tr>
<tr class="row-6 even">
<td class="column-1">5</td><td class="column-2">AJ Networks</td><td class="column-3">095570</td>
</tr>
<tr class="row-7 odd">
<td class="column-1">6</td><td class="column-2">AJ RENT A CAR</td><td class="column-3">068400</td>
</tr>
<tr class="row-8 even">
<td class="column-1">7</td><td class="column-2">AJU CAPITAL</td><td class="column-3">033660</td>
</tr>
<tr class="row-9 odd">
<td class="column-1">8</td><td class="column-2">AK Holdings</td><td class="column-3">006840</td>
</tr>
<tr class="row-10 even">
<td class="column-1">9</td><td class="column-2">AK Petrochemical</td><td class="column-3">161000</td>
</tr>
<tr class="row-11 odd">
<td class="column-1">10</td><td class="column-2">ALUKO</td><td class="column-3">001780</td>
</tr>
<tr class="row-12 even">
<td class="column-1">11</td><td class="column-2">ALVOGEN KOREA</td><td class="column-3">002250</td>
</tr>
<tr class="row-13 odd">
<td class="column-1">12</td><td class="column-2">AmoreG</td><td class="column-3">002790</td>
</tr>
<tr class="row-14 even">
<td class="column-1">13</td><td class="column-2">AmoreG(1P)</td><td class="column-3">002795</td>
</tr>
<tr class="row-15 odd">
<td class="column-1">14</td><td class="column-2">AMOREPACIFIC</td><td class="column-3">090430</td>
</tr>
<tr class="row-16 even">
<td class="column-1">15</td><td class="column-2">AMOREPACIFIC(1P)</td><td class="column-3">090435</td>
</tr>
<tr class="row-17 odd">
<td class="column-1">16</td><td class="column-2">AnamElec</td><td class="column-3">008700</td>
</tr>
<tr class="row-18 even">
<td class="column-1">17</td><td class="column-2">Aprogen KIC</td><td class="column-3">007460</td>
</tr>
<tr class="row-19 odd">
<td class="column-1">18</td><td class="column-2">Aprogen pharmaceuticals</td><td class="column-3">003060</td>
</tr>
<tr class="row-20 even">
<td class="column-1">19</td><td class="column-2">ARTIS</td><td class="column-3">101140</td>
</tr>
<tr class="row-21 odd">
<td class="column-1">20</td><td class="column-2">ASIA HOLDINGS</td><td class="column-3">002030</td>
</tr>
<tr class="row-22 even">
<td class="column-1">21</td><td class="column-2">ASIACEMENT</td><td class="column-3">183190</td>
</tr>
<tr class="row-23 odd">
<td class="column-1">22</td><td class="column-2">Asiana Airlines</td><td class="column-3">020560</td>
</tr>
<tr class="row-24 even">
<td class="column-1">23</td><td class="column-2">AsiaPaprMfg</td><td class="column-3">002310</td>
</tr>
<tr class="row-25 odd">
<td class="column-1">24</td><td class="column-2">AUK</td><td class="column-3">017900</td>
</tr>
<tr class="row-26 even">
<td class="column-1">25</td><td class="column-2">Badaro19</td><td class="column-3">155900</td>
</tr>
<tr class="row-27 odd">
<td class="column-1">26</td><td class="column-2">BaekkwangMinPdt</td><td class="column-3">014580</td>
</tr>
<tr class="row-28 even">
<td class="column-1">27</td><td class="column-2">Baiksan</td><td class="column-3">035150</td>
</tr>
<tr class="row-29 odd">
<td class="column-1">28</td><td class="column-2">BGF</td><td class="column-3">027410</td>
</tr>
<tr class="row-30 even">
<td class="column-1">29</td><td class="column-2">BGF Retail</td><td class="column-3">282330</td>
</tr>
<tr class="row-31 odd">
<td class="column-1">30</td><td class="column-2">Binggrae</td><td class="column-3">005180</td>
</tr>
<tr class="row-32 even">
<td class="column-1">31</td><td class="column-2">BNK Financial Group</td><td class="column-3">138930</td>
</tr>
<tr class="row-33 odd">
<td class="column-1">32</td><td class="column-2">BohaeBrew</td><td class="column-3">000890</td>
</tr>
<tr class="row-34 even">
<td class="column-1">33</td><td class="column-2">Bolak</td><td class="column-3">002760</td>
</tr>
<tr class="row-35 odd">
<td class="column-1">34</td><td class="column-2">Bookook Steel</td><td class="column-3">026940</td>
</tr>
<tr class="row-36 even">
<td class="column-1">35</td><td class="column-2">BookookSecu</td><td class="column-3">001270</td>
</tr>
<tr class="row-37 odd">
<td class="column-1">36</td><td class="column-2">BookookSecu(1P)</td><td class="column-3">001275</td>
</tr>
<tr class="row-38 even">
<td class="column-1">37</td><td class="column-2">BoryungPharm</td><td class="column-3">003850</td>
</tr>
<tr class="row-39 odd">
<td class="column-1">38</td><td class="column-2">BukwangPharm</td><td class="column-3">003000</td>
</tr>
<tr class="row-40 even">
<td class="column-1">39</td><td class="column-2">BUMYANG CONST</td><td class="column-3">002410</td>
</tr>
<tr class="row-41 odd">
<td class="column-1">40</td><td class="column-2">BusanCtyGas</td><td class="column-3">015350</td>
</tr>
<tr class="row-42 even">
<td class="column-1">41</td><td class="column-2">BusanInd</td><td class="column-3">011390</td>
</tr>
<tr class="row-43 odd">
<td class="column-1">42</td><td class="column-2">BYC</td><td class="column-3">001460</td>
</tr>
<tr class="row-44 even">
<td class="column-1">43</td><td class="column-2">BYC(1P)</td><td class="column-3">001465</td>
</tr>
<tr class="row-45 odd">
<td class="column-1">44</td><td class="column-2">Byuksan</td><td class="column-3">007210</td>
</tr>
<tr class="row-46 even">
<td class="column-1">45</td><td class="column-2">CAMUS E&amp;S</td><td class="column-3">013700</td>
</tr>
<tr class="row-47 odd">
<td class="column-1">46</td><td class="column-2">CAPRO</td><td class="column-3">006380</td>
</tr>
<tr class="row-48 even">
<td class="column-1">47</td><td class="column-2">Celltrion</td><td class="column-3">068270</td>
</tr>
<tr class="row-49 odd">
<td class="column-1">48</td><td class="column-2">Century</td><td class="column-3">002420</td>
</tr>
<tr class="row-50 even">
<td class="column-1">49</td><td class="column-2">Charm Engineering</td><td class="column-3">009310</td>
</tr>
<tr class="row-51 odd">
<td class="column-1">50</td><td class="column-2">CHASYS</td><td class="column-3">033250</td>
</tr>
<tr class="row-52 even">
<td class="column-1">51</td><td class="column-2">CHEILGRINDING</td><td class="column-3">001560</td>
</tr>
<tr class="row-53 odd">
<td class="column-1">52</td><td class="column-2">CheilWorldwide</td><td class="column-3">030000</td>
</tr>
<tr class="row-54 even">
<td class="column-1">53</td><td class="column-2">CHINHUNG INT (2PB)</td><td class="column-3">002787</td>
</tr>
<tr class="row-55 odd">
<td class="column-1">54</td><td class="column-2">CHINHUNG INT(1PB)</td><td class="column-3">002785</td>
</tr>
<tr class="row-56 even">
<td class="column-1">55</td><td class="column-2">ChinhungInt</td><td class="column-3">002780</td>
</tr>
<tr class="row-57 odd">
<td class="column-1">56</td><td class="column-2">Chinyang Holdings</td><td class="column-3">100250</td>
</tr>
<tr class="row-58 even">
<td class="column-1">57</td><td class="column-2">Chinyang Industry</td><td class="column-3">003780</td>
</tr>
<tr class="row-59 odd">
<td class="column-1">58</td><td class="column-2">ChinYangChem</td><td class="column-3">051630</td>
</tr>
<tr class="row-60 even">
<td class="column-1">59</td><td class="column-2">ChinYangPoly</td><td class="column-3">010640</td>
</tr>
<tr class="row-61 odd">
<td class="column-1">60</td><td class="column-2">Chobi</td><td class="column-3">001550</td>
</tr>
<tr class="row-62 even">
<td class="column-1">61</td><td class="column-2">CHOHEUNG</td><td class="column-3">002600</td>
</tr>
<tr class="row-63 odd">
<td class="column-1">62</td><td class="column-2">CHOILALUMINUM</td><td class="column-3">018470</td>
</tr>
<tr class="row-64 even">
<td class="column-1">63</td><td class="column-2">ChokwangLeat</td><td class="column-3">004700</td>
</tr>
<tr class="row-65 odd">
<td class="column-1">64</td><td class="column-2">ChokwangPaint</td><td class="column-3">004910</td>
</tr>
<tr class="row-66 even">
<td class="column-1">65</td><td class="column-2">Chonbang</td><td class="column-3">000950</td>
</tr>
<tr class="row-67 odd">
<td class="column-1">66</td><td class="column-2">CHONGKUNDANG</td><td class="column-3">185750</td>
</tr>
<tr class="row-68 even">
<td class="column-1">67</td><td class="column-2">CHONGKUNDANG HOLDINGS</td><td class="column-3">001630</td>
</tr>
<tr class="row-69 odd">
<td class="column-1">68</td><td class="column-2">CHOSUN WELDING</td><td class="column-3">120030</td>
</tr>
<tr class="row-70 even">
<td class="column-1">69</td><td class="column-2">ChosunRefrctr</td><td class="column-3">000480</td>
</tr>
<tr class="row-71 odd">
<td class="column-1">70</td><td class="column-2">CHUNGHO</td><td class="column-3">012600</td>
</tr>
<tr class="row-72 even">
<td class="column-1">71</td><td class="column-2">ChunilExp</td><td class="column-3">000650</td>
</tr>
<tr class="row-73 odd">
<td class="column-1">72</td><td class="column-2">CITECH</td><td class="column-3">004920</td>
</tr>
<tr class="row-74 even">
<td class="column-1">73</td><td class="column-2">CJ</td><td class="column-3">001040</td>
</tr>
<tr class="row-75 odd">
<td class="column-1">74</td><td class="column-2">CJ CGV</td><td class="column-3">079160</td>
</tr>
<tr class="row-76 even">
<td class="column-1">75</td><td class="column-2">CJ CheilJedang</td><td class="column-3">097950</td>
</tr>
<tr class="row-77 odd">
<td class="column-1">76</td><td class="column-2">CJ CheilJedang(1P)</td><td class="column-3">097955</td>
</tr>
<tr class="row-78 even">
<td class="column-1">77</td><td class="column-2">CJ Hello</td><td class="column-3">037560</td>
</tr>
<tr class="row-79 odd">
<td class="column-1">78</td><td class="column-2">CJ LOGISTICS</td><td class="column-3">000120</td>
</tr>
<tr class="row-80 even">
<td class="column-1">79</td><td class="column-2">CJ(1P)</td><td class="column-3">001045</td>
</tr>
<tr class="row-81 odd">
<td class="column-1">80</td><td class="column-2">CJSEAFOOD</td><td class="column-3">011150</td>
</tr>
<tr class="row-82 even">
<td class="column-1">81</td><td class="column-2">CJSEAFOOD(1P)</td><td class="column-3">011155</td>
</tr>
<tr class="row-83 odd">
<td class="column-1">82</td><td class="column-2">CKDBio</td><td class="column-3">063160</td>
</tr>
<tr class="row-84 even">
<td class="column-1">83</td><td class="column-2">Comtec</td><td class="column-3">031820</td>
</tr>
<tr class="row-85 odd">
<td class="column-1">84</td><td class="column-2">CONBUZZ</td><td class="column-3">109070</td>
</tr>
<tr class="row-86 even">
<td class="column-1">85</td><td class="column-2">COSMAX</td><td class="column-3">192820</td>
</tr>
<tr class="row-87 odd">
<td class="column-1">86</td><td class="column-2">COSMAX bti</td><td class="column-3">044820</td>
</tr>
<tr class="row-88 even">
<td class="column-1">87</td><td class="column-2">CosmoAM&amp;T</td><td class="column-3">005070</td>
</tr>
<tr class="row-89 odd">
<td class="column-1">88</td><td class="column-2">COSMOCHEM</td><td class="column-3">005420</td>
</tr>
<tr class="row-90 even">
<td class="column-1">89</td><td class="column-2">COWAY</td><td class="column-3">021240</td>
</tr>
<tr class="row-91 odd">
<td class="column-1">90</td><td class="column-2">CROWN</td><td class="column-3">264900</td>
</tr>
<tr class="row-92 even">
<td class="column-1">91</td><td class="column-2">CROWN(1P)</td><td class="column-3">26490K</td>
</tr>
<tr class="row-93 odd">
<td class="column-1">92</td><td class="column-2">CROWNHAITAI Holdings</td><td class="column-3">005740</td>
</tr>
<tr class="row-94 even">
<td class="column-1">93</td><td class="column-2">CROWNHAITAI Holdings(1P)</td><td class="column-3">005745</td>
</tr>
<tr class="row-95 odd">
<td class="column-1">94</td><td class="column-2">CSHOLDINGS</td><td class="column-3">000590</td>
</tr>
<tr class="row-96 even">
<td class="column-1">95</td><td class="column-2">CSWIND</td><td class="column-3">112610</td>
</tr>
<tr class="row-97 odd">
<td class="column-1">96</td><td class="column-2">CUCKOO</td><td class="column-3">192400</td>
</tr>
<tr class="row-98 even">
<td class="column-1">97</td><td class="column-2">CUCKOO HOMESYS</td><td class="column-3">284740</td>
</tr>
<tr class="row-99 odd">
<td class="column-1">98</td><td class="column-2">CURO</td><td class="column-3">015590</td>
</tr>
<tr class="row-100 even">
<td class="column-1">99</td><td class="column-2">DAECHANG</td><td class="column-3">012800</td>
</tr>
<tr class="row-101 odd">
<td class="column-1">100</td><td class="column-2">DaechangForging</td><td class="column-3">015230</td>
</tr>
<tr class="row-102 even">
<td class="column-1">101</td><td class="column-2">Daedong</td><td class="column-3">000490</td>
</tr>
<tr class="row-103 odd">
<td class="column-1">102</td><td class="column-2">DAEDUCK(1P)</td><td class="column-3">004135</td>
</tr>
<tr class="row-104 even">
<td class="column-1">103</td><td class="column-2">DaeduckElec</td><td class="column-3">008060</td>
</tr>
<tr class="row-105 odd">
<td class="column-1">104</td><td class="column-2">DAEDUCKGDS</td><td class="column-3">004130</td>
</tr>
<tr class="row-106 even">
<td class="column-1">105</td><td class="column-2">DaeguDptStr</td><td class="column-3">006370</td>
</tr>
<tr class="row-107 odd">
<td class="column-1">106</td><td class="column-2">Daehan Steel</td><td class="column-3">084010</td>
</tr>
<tr class="row-108 even">
<td class="column-1">107</td><td class="column-2">DaehanFlrMill</td><td class="column-3">001130</td>
</tr>
<tr class="row-109 odd">
<td class="column-1">108</td><td class="column-2">DaehanSynthFibr</td><td class="column-3">003830</td>
</tr>
<tr class="row-110 even">
<td class="column-1">109</td><td class="column-2">DAEHOAL</td><td class="column-3">069460</td>
</tr>
<tr class="row-111 odd">
<td class="column-1">110</td><td class="column-2">Daehyun</td><td class="column-3">016090</td>
</tr>
<tr class="row-112 even">
<td class="column-1">111</td><td class="column-2">DAEKYO</td><td class="column-3">019680</td>
</tr>
<tr class="row-113 odd">
<td class="column-1">112</td><td class="column-2">DAEKYO(1PB)</td><td class="column-3">019685</td>
</tr>
<tr class="row-114 even">
<td class="column-1">113</td><td class="column-2">DAELIM B&amp;Co</td><td class="column-3">005750</td>
</tr>
<tr class="row-115 odd">
<td class="column-1">114</td><td class="column-2">DAELIM C&amp;S</td><td class="column-3">004440</td>
</tr>
<tr class="row-116 even">
<td class="column-1">115</td><td class="column-2">DaelimInd</td><td class="column-3">000210</td>
</tr>
<tr class="row-117 odd">
<td class="column-1">116</td><td class="column-2">DaelimInd(1P)</td><td class="column-3">000215</td>
</tr>
<tr class="row-118 even">
<td class="column-1">117</td><td class="column-2">DaelimTrdg</td><td class="column-3">006570</td>
</tr>
<tr class="row-119 odd">
<td class="column-1">118</td><td class="column-2">Daesang</td><td class="column-3">001680</td>
</tr>
<tr class="row-120 even">
<td class="column-1">119</td><td class="column-2">Daesang Holdings</td><td class="column-3">084690</td>
</tr>
<tr class="row-121 odd">
<td class="column-1">120</td><td class="column-2">Daesang Holdings(1P)</td><td class="column-3">084695</td>
</tr>
<tr class="row-122 even">
<td class="column-1">121</td><td class="column-2">Daesang(1P)</td><td class="column-3">001685</td>
</tr>
<tr class="row-123 odd">
<td class="column-1">122</td><td class="column-2">DAESUNG HOLDINGS</td><td class="column-3">016710</td>
</tr>
<tr class="row-124 even">
<td class="column-1">123</td><td class="column-2">DAESUNGENERGY</td><td class="column-3">117580</td>
</tr>
<tr class="row-125 odd">
<td class="column-1">124</td><td class="column-2">DAESUNGIND</td><td class="column-3">128820</td>
</tr>
<tr class="row-126 even">
<td class="column-1">125</td><td class="column-2">DaewonCbl</td><td class="column-3">006340</td>
</tr>
<tr class="row-127 odd">
<td class="column-1">126</td><td class="column-2">DaewonCbl(1P)</td><td class="column-3">006345</td>
</tr>
<tr class="row-128 even">
<td class="column-1">127</td><td class="column-2">DaewonChem</td><td class="column-3">024890</td>
</tr>
<tr class="row-129 odd">
<td class="column-1">128</td><td class="column-2">DaewonKangup</td><td class="column-3">000430</td>
</tr>
<tr class="row-130 even">
<td class="column-1">129</td><td class="column-2">Daewonpharm</td><td class="column-3">003220</td>
</tr>
<tr class="row-131 odd">
<td class="column-1">130</td><td class="column-2">DAEWOOELECCOMPONENTS</td><td class="column-3">009320</td>
</tr>
<tr class="row-132 even">
<td class="column-1">131</td><td class="column-2">Daewoong</td><td class="column-3">003090</td>
</tr>
<tr class="row-133 odd">
<td class="column-1">132</td><td class="column-2">DAEWOONG PHARM</td><td class="column-3">069620</td>
</tr>
<tr class="row-134 even">
<td class="column-1">133</td><td class="column-2">DaeyoungPkg</td><td class="column-3">014160</td>
</tr>
<tr class="row-135 odd">
<td class="column-1">134</td><td class="column-2">DAIDONG</td><td class="column-3">008110</td>
</tr>
<tr class="row-136 even">
<td class="column-1">135</td><td class="column-2">DaishinSecu</td><td class="column-3">003540</td>
</tr>
<tr class="row-137 odd">
<td class="column-1">136</td><td class="column-2">DaishinSecu(1P)</td><td class="column-3">003545</td>
</tr>
<tr class="row-138 even">
<td class="column-1">137</td><td class="column-2">DAISHINSECU(2PB)</td><td class="column-3">003547</td>
</tr>
<tr class="row-139 odd">
<td class="column-1">138</td><td class="column-2">DaiyangMtl</td><td class="column-3">009190</td>
</tr>
<tr class="row-140 even">
<td class="column-1">139</td><td class="column-2">DaouTech</td><td class="column-3">023590</td>
</tr>
<tr class="row-141 odd">
<td class="column-1">140</td><td class="column-2">DASCO</td><td class="column-3">058730</td>
</tr>
<tr class="row-142 even">
<td class="column-1">141</td><td class="column-2">DAYOU A-TECH</td><td class="column-3">002880</td>
</tr>
<tr class="row-143 odd">
<td class="column-1">142</td><td class="column-2">DAYOUPLUS</td><td class="column-3">000300</td>
</tr>
<tr class="row-144 even">
<td class="column-1">143</td><td class="column-2">DB</td><td class="column-3">012030</td>
</tr>
<tr class="row-145 odd">
<td class="column-1">144</td><td class="column-2">DB HiTek</td><td class="column-3">000990</td>
</tr>
<tr class="row-146 even">
<td class="column-1">145</td><td class="column-2">DB HiTek(1P)</td><td class="column-3">000995</td>
</tr>
<tr class="row-147 odd">
<td class="column-1">146</td><td class="column-2">DB INSURANCE</td><td class="column-3">005830</td>
</tr>
<tr class="row-148 even">
<td class="column-1">147</td><td class="column-2">DBFI</td><td class="column-3">016610</td>
</tr>
<tr class="row-149 odd">
<td class="column-1">148</td><td class="column-2">DCM</td><td class="column-3">024090</td>
</tr>
<tr class="row-150 even">
<td class="column-1">149</td><td class="column-2">DENTIUM</td><td class="column-3">145720</td>
</tr>
<tr class="row-151 odd">
<td class="column-1">150</td><td class="column-2">DGB Financial Group</td><td class="column-3">139130</td>
</tr>
<tr class="row-152 even">
<td class="column-1">151</td><td class="column-2">DHICO</td><td class="column-3">034020</td>
</tr>
<tr class="row-153 odd">
<td class="column-1">152</td><td class="column-2">DI</td><td class="column-3">003160</td>
</tr>
<tr class="row-154 even">
<td class="column-1">153</td><td class="column-2">DIC</td><td class="column-3">004890</td>
</tr>
<tr class="row-155 odd">

In [5]:
print(table.findAll('tr'))

[<tr class="row-1 odd">
<th class="column-1">S.No.</th><th class="column-2">Name</th><th class="column-3">Code</th>
</tr>, <tr class="row-2 even">
<td class="column-1">1</td><td class="column-2">A REIT</td><td class="column-3">140910</td>
</tr>, <tr class="row-3 odd">
<td class="column-1">2</td><td class="column-2">A&amp;P</td><td class="column-3">015260</td>
</tr>, <tr class="row-4 even">
<td class="column-1">3</td><td class="column-2">ABLE C&amp;C</td><td class="column-3">078520</td>
</tr>, <tr class="row-5 odd">
<td class="column-1">4</td><td class="column-2">AEKYUNG INDUSTRIAL</td><td class="column-3">018250</td>
</tr>, <tr class="row-6 even">
<td class="column-1">5</td><td class="column-2">AJ Networks</td><td class="column-3">095570</td>
</tr>, <tr class="row-7 odd">
<td class="column-1">6</td><td class="column-2">AJ RENT A CAR</td><td class="column-3">068400</td>
</tr>, <tr class="row-8 even">
<td class="column-1">7</td><td class="column-2">AJU CAPITAL</td><td class="column-3">033660</td>
</tr>, <tr class="row-9 odd">
<td class="column-1">8</td><td class="column-2">AK Holdings</td><td class="column-3">006840</td>
</tr>, <tr class="row-10 even">
<td class="column-1">9</td><td class="column-2">AK Petrochemical</td><td class="column-3">161000</td>
</tr>, <tr class="row-11 odd">
<td class="column-1">10</td><td class="column-2">ALUKO</td><td class="column-3">001780</td>
</tr>, <tr class="row-12 even">
<td class="column-1">11</td><td class="column-2">ALVOGEN KOREA</td><td class="column-3">002250</td>
</tr>, <tr class="row-13 odd">
<td class="column-1">12</td><td class="column-2">AmoreG</td><td class="column-3">002790</td>
</tr>, <tr class="row-14 even">
<td class="column-1">13</td><td class="column-2">AmoreG(1P)</td><td class="column-3">002795</td>
</tr>, <tr class="row-15 odd">
<td class="column-1">14</td><td class="column-2">AMOREPACIFIC</td><td class="column-3">090430</td>
</tr>, <tr class="row-16 even">
<td class="column-1">15</td><td class="column-2">AMOREPACIFIC(1P)</td><td class="column-3">090435</td>
</tr>, <tr class="row-17 odd">
<td class="column-1">16</td><td class="column-2">AnamElec</td><td class="column-3">008700</td>
</tr>, <tr class="row-18 even">
<td class="column-1">17</td><td class="column-2">Aprogen KIC</td><td class="column-3">007460</td>
</tr>, <tr class="row-19 odd">
<td class="column-1">18</td><td class="column-2">Aprogen pharmaceuticals</td><td class="column-3">003060</td>
</tr>, <tr class="row-20 even">
<td class="column-1">19</td><td class="column-2">ARTIS</td><td class="column-3">101140</td>
</tr>, <tr class="row-21 odd">
<td class="column-1">20</td><td class="column-2">ASIA HOLDINGS</td><td class="column-3">002030</td>
</tr>, <tr class="row-22 even">
<td class="column-1">21</td><td class="column-2">ASIACEMENT</td><td class="column-3">183190</td>
</tr>, <tr class="row-23 odd">
<td class="column-1">22</td><td class="column-2">Asiana Airlines</td><td class="column-3">020560</td>
</tr>, <tr class="row-24 even">
<td class="column-1">23</td><td class="column-2">AsiaPaprMfg</td><td class="column-3">002310</td>
</tr>, <tr class="row-25 odd">
<td class="column-1">24</td><td class="column-2">AUK</td><td class="column-3">017900</td>
</tr>, <tr class="row-26 even">
<td class="column-1">25</td><td class="column-2">Badaro19</td><td class="column-3">155900</td>
</tr>, <tr class="row-27 odd">
<td class="column-1">26</td><td class="column-2">BaekkwangMinPdt</td><td class="column-3">014580</td>
</tr>, <tr class="row-28 even">
<td class="column-1">27</td><td class="column-2">Baiksan</td><td class="column-3">035150</td>
</tr>, <tr class="row-29 odd">
<td class="column-1">28</td><td class="column-2">BGF</td><td class="column-3">027410</td>
</tr>, <tr class="row-30 even">
<td class="column-1">29</td><td class="column-2">BGF Retail</td><td class="column-3">282330</td>
</tr>, <tr class="row-31 odd">
<td class="column-1">30</td><td class="column-2">Binggrae</td><td class="column-3">005180</td>
</tr>, <tr class="row-32 even">
<td class="column-1">31</td><td class="column-2">BNK Financial Group</td><td class="column-3">138930</td>
</tr>, <tr class="row-33 odd">
<td class="column-1">32</td><td class="column-2">BohaeBrew</td><td class="column-3">000890</td>
</tr>, <tr class="row-34 even">
<td class="column-1">33</td><td class="column-2">Bolak</td><td class="column-3">002760</td>
</tr>, <tr class="row-35 odd">
<td class="column-1">34</td><td class="column-2">Bookook Steel</td><td class="column-3">026940</td>
</tr>, <tr class="row-36 even">
<td class="column-1">35</td><td class="column-2">BookookSecu</td><td class="column-3">001270</td>
</tr>, <tr class="row-37 odd">
<td class="column-1">36</td><td class="column-2">BookookSecu(1P)</td><td class="column-3">001275</td>
</tr>, <tr class="row-38 even">
<td class="column-1">37</td><td class="column-2">BoryungPharm</td><td class="column-3">003850</td>
</tr>, <tr class="row-39 odd">
<td class="column-1">38</td><td class="column-2">BukwangPharm</td><td class="column-3">003000</td>
</tr>, <tr class="row-40 even">
<td class="column-1">39</td><td class="column-2">BUMYANG CONST</td><td class="column-3">002410</td>
</tr>, <tr class="row-41 odd">
<td class="column-1">40</td><td class="column-2">BusanCtyGas</td><td class="column-3">015350</td>
</tr>, <tr class="row-42 even">
<td class="column-1">41</td><td class="column-2">BusanInd</td><td class="column-3">011390</td>
</tr>, <tr class="row-43 odd">
<td class="column-1">42</td><td class="column-2">BYC</td><td class="column-3">001460</td>
</tr>, <tr class="row-44 even">
<td class="column-1">43</td><td class="column-2">BYC(1P)</td><td class="column-3">001465</td>
</tr>, <tr class="row-45 odd">
<td class="column-1">44</td><td class="column-2">Byuksan</td><td class="column-3">007210</td>
</tr>, <tr class="row-46 even">
<td class="column-1">45</td><td class="column-2">CAMUS E&amp;S</td><td class="column-3">013700</td>
</tr>, <tr class="row-47 odd">
<td class="column-1">46</td><td class="column-2">CAPRO</td><td class="column-3">006380</td>
</tr>, <tr class="row-48 even">
<td class="column-1">47</td><td class="column-2">Celltrion</td><td class="column-3">068270</td>
</tr>, <tr class="row-49 odd">
<td class="column-1">48</td><td class="column-2">Century</td><td class="column-3">002420</td>
</tr>, <tr class="row-50 even">
<td class="column-1">49</td><td class="column-2">Charm Engineering</td><td class="column-3">009310</td>
</tr>, <tr class="row-51 odd">
<td class="column-1">50</td><td class="column-2">CHASYS</td><td class="column-3">033250</td>
</tr>, <tr class="row-52 even">
<td class="column-1">51</td><td class="column-2">CHEILGRINDING</td><td class="column-3">001560</td>
</tr>, <tr class="row-53 odd">
<td class="column-1">52</td><td class="column-2">CheilWorldwide</td><td class="column-3">030000</td>
</tr>, <tr class="row-54 even">
<td class="column-1">53</td><td class="column-2">CHINHUNG INT (2PB)</td><td class="column-3">002787</td>
</tr>, <tr class="row-55 odd">
<td class="column-1">54</td><td class="column-2">CHINHUNG INT(1PB)</td><td class="column-3">002785</td>
</tr>, <tr class="row-56 even">
<td class="column-1">55</td><td class="column-2">ChinhungInt</td><td class="column-3">002780</td>
</tr>, <tr class="row-57 odd">
<td class="column-1">56</td><td class="column-2">Chinyang Holdings</td><td class="column-3">100250</td>
</tr>, <tr class="row-58 even">
<td class="column-1">57</td><td class="column-2">Chinyang Industry</td><td class="column-3">003780</td>
</tr>, <tr class="row-59 odd">
<td class="column-1">58</td><td class="column-2">ChinYangChem</td><td class="column-3">051630</td>
</tr>, <tr class="row-60 even">
<td class="column-1">59</td><td class="column-2">ChinYangPoly</td><td class="column-3">010640</td>
</tr>, <tr class="row-61 odd">
<td class="column-1">60</td><td class="column-2">Chobi</td><td class="column-3">001550</td>
</tr>, <tr class="row-62 even">
<td class="column-1">61</td><td class="column-2">CHOHEUNG</td><td class="column-3">002600</td>
</tr>, <tr class="row-63 odd">
<td class="column-1">62</td><td class="column-2">CHOILALUMINUM</td><td class="column-3">018470</td>
</tr>, <tr class="row-64 even">
<td class="column-1">63</td><td class="column-2">ChokwangLeat</td><td class="column-3">004700</td>
</tr>, <tr class="row-65 odd">
<td class="column-1">64</td><td class="column-2">ChokwangPaint</td><td class="column-3">004910</td>
</tr>, <tr class="row-66 even">
<td class="column-1">65</td><td class="column-2">Chonbang</td><td class="column-3">000950</td>
</tr>, <tr class="row-67 odd">
<td class="column-1">66</td><td class="column-2">CHONGKUNDANG</td><td class="column-3">185750</td>
</tr>, <tr class="row-68 even">
<td class="column-1">67</td><td class="column-2">CHONGKUNDANG HOLDINGS</td><td class="column-3">001630</td>
</tr>, <tr class="row-69 odd">
<td class="column-1">68</td><td class="column-2">CHOSUN WELDING</td><td class="column-3">120030</td>
</tr>, <tr class="row-70 even">
<td class="column-1">69</td><td class="column-2">ChosunRefrctr</td><td class="column-3">000480</td>
</tr>, <tr class="row-71 odd">
<td class="column-1">70</td><td class="column-2">CHUNGHO</td><td class="column-3">012600</td>
</tr>, <tr class="row-72 even">
<td class="column-1">71</td><td class="column-2">ChunilExp</td><td class="column-3">000650</td>
</tr>, <tr class="row-73 odd">
<td class="column-1">72</td><td class="column-2">CITECH</td><td class="column-3">004920</td>
</tr>, <tr class="row-74 even">
<td class="column-1">73</td><td class="column-2">CJ</td><td class="column-3">001040</td>
</tr>, <tr class="row-75 odd">
<td class="column-1">74</td><td class="column-2">CJ CGV</td><td class="column-3">079160</td>
</tr>, <tr class="row-76 even">
<td class="column-1">75</td><td class="column-2">CJ CheilJedang</td><td class="column-3">097950</td>
</tr>, <tr class="row-77 odd">
<td class="column-1">76</td><td class="column-2">CJ CheilJedang(1P)</td><td class="column-3">097955</td>
</tr>, <tr class="row-78 even">
<td class="column-1">77</td><td class="column-2">CJ Hello</td><td class="column-3">037560</td>
</tr>, <tr class="row-79 odd">
<td class="column-1">78</td><td class="column-2">CJ LOGISTICS</td><td class="column-3">000120</td>
</tr>, <tr class="row-80 even">
<td class="column-1">79</td><td class="column-2">CJ(1P)</td><td class="column-3">001045</td>
</tr>, <tr class="row-81 odd">
<td class="column-1">80</td><td class="column-2">CJSEAFOOD</td><td class="column-3">011150</td>
</tr>, <tr class="row-82 even">
<td class="column-1">81</td><td class="column-2">CJSEAFOOD(1P)</td><td class="column-3">011155</td>
</tr>, <tr class="row-83 odd">
<td class="column-1">82</td><td class="column-2">CKDBio</td><td class="column-3">063160</td>
</tr>, <tr class="row-84 even">
<td class="column-1">83</td><td class="column-2">Comtec</td><td class="column-3">031820</td>
</tr>, <tr class="row-85 odd">
<td class="column-1">84</td><td class="column-2">CONBUZZ</td><td class="column-3">109070</td>
</tr>, <tr class="row-86 even">
<td class="column-1">85</td><td class="column-2">COSMAX</td><td class="column-3">192820</td>
</tr>, <tr class="row-87 odd">
<td class="column-1">86</td><td class="column-2">COSMAX bti</td><td class="column-3">044820</td>
</tr>, <tr class="row-88 even">
<td class="column-1">87</td><td class="column-2">CosmoAM&amp;T</td><td class="column-3">005070</td>
</tr>, <tr class="row-89 odd">
<td class="column-1">88</td><td class="column-2">COSMOCHEM</td><td class="column-3">005420</td>
</tr>, <tr class="row-90 even">
<td class="column-1">89</td><td class="column-2">COWAY</td><td class="column-3">021240</td>
</tr>, <tr class="row-91 odd">
<td class="column-1">90</td><td class="column-2">CROWN</td><td class="column-3">264900</td>
</tr>, <tr class="row-92 even">
<td class="column-1">91</td><td class="column-2">CROWN(1P)</td><td class="column-3">26490K</td>
</tr>, <tr class="row-93 odd">
<td class="column-1">92</td><td class="column-2">CROWNHAITAI Holdings</td><td class="column-3">005740</td>
</tr>, <tr class="row-94 even">
<td class="column-1">93</td><td class="column-2">CROWNHAITAI Holdings(1P)</td><td class="column-3">005745</td>
</tr>, <tr class="row-95 odd">
<td class="column-1">94</td><td class="column-2">CSHOLDINGS</td><td class="column-3">000590</td>
</tr>, <tr class="row-96 even">
<td class="column-1">95</td><td class="column-2">CSWIND</td><td class="column-3">112610</td>
</tr>, <tr class="row-97 odd">
<td class="column-1">96</td><td class="column-2">CUCKOO</td><td class="column-3">192400</td>
</tr>, <tr class="row-98 even">
<td class="column-1">97</td><td class="column-2">CUCKOO HOMESYS</td><td class="column-3">284740</td>
</tr>, <tr class="row-99 odd">
<td class="column-1">98</td><td class="column-2">CURO</td><td class="column-3">015590</td>
</tr>, <tr class="row-100 even">
<td class="column-1">99</td><td class="column-2">DAECHANG</td><td class="column-3">012800</td>
</tr>, <tr class="row-101 odd">
<td class="column-1">100</td><td class="column-2">DaechangForging</td><td class="column-3">015230</td>
</tr>, <tr class="row-102 even">
<td class="column-1">101</td><td class="column-2">Daedong</td><td class="column-3">000490</td>
</tr>, <tr class="row-103 odd">
<td class="column-1">102</td><td class="column-2">DAEDUCK(1P)</td><td class="column-3">004135</td>
</tr>, <tr class="row-104 even">
<td class="column-1">103</td><td class="column-2">DaeduckElec</td><td class="column-3">008060</td>
</tr>, <tr class="row-105 odd">
<td class="column-1">104</td><td class="column-2">DAEDUCKGDS</td><td class="column-3">004130</td>
</tr>, <tr class="row-106 even">
<td class="column-1">105</td><td class="column-2">DaeguDptStr</td><td class="column-3">006370</td>
</tr>, <tr class="row-107 odd">
<td class="column-1">106</td><td class="column-2">Daehan Steel</td><td class="column-3">084010</td>
</tr>, <tr class="row-108 even">
<td class="column-1">107</td><td class="column-2">DaehanFlrMill</td><td class="column-3">001130</td>
</tr>, <tr class="row-109 odd">
<td class="column-1">108</td><td class="column-2">DaehanSynthFibr</td><td class="column-3">003830</td>
</tr>, <tr class="row-110 even">
<td class="column-1">109</td><td class="column-2">DAEHOAL</td><td class="column-3">069460</td>
</tr>, <tr class="row-111 odd">
<td class="column-1">110</td><td class="column-2">Daehyun</td><td class="column-3">016090</td>
</tr>, <tr class="row-112 even">
<td class="column-1">111</td><td class="column-2">DAEKYO</td><td class="column-3">019680</td>
</tr>, <tr class="row-113 odd">
<td class="column-1">112</td><td class="column-2">DAEKYO(1PB)</td><td class="column-3">019685</td>
</tr>, <tr class="row-114 even">
<td class="column-1">113</td><td class="column-2">DAELIM B&amp;Co</td><td class="column-3">005750</td>
</tr>, <tr class="row-115 odd">
<td class="column-1">114</td><td class="column-2">DAELIM C&amp;S</td><td class="column-3">004440</td>
</tr>, <tr class="row-116 even">
<td class="column-1">115</td><td class="column-2">DaelimInd</td><td class="column-3">000210</td>
</tr>, <tr class="row-117 odd">
<td class="column-1">116</td><td class="column-2">DaelimInd(1P)</td><td class="column-3">000215</td>
</tr>, <tr class="row-118 even">
<td class="column-1">117</td><td class="column-2">DaelimTrdg</td><td class="column-3">006570</td>
</tr>, <tr class="row-119 odd">
<td class="column-1">118</td><td class="column-2">Daesang</td><td class="column-3">001680</td>
</tr>, <tr class="row-120 even">
<td class="column-1">119</td><td class="column-2">Daesang Holdings</td><td class="column-3">084690</td>
</tr>, <tr class="row-121 odd">
<td class="column-1">120</td><td class="column-2">Daesang Holdings(1P)</td><td class="column-3">084695</td>
</tr>, <tr class="row-122 even">
<td class="column-1">121</td><td class="column-2">Daesang(1P)</td><td class="column-3">001685</td>
</tr>, <tr class="row-123 odd">
<td class="column-1">122</td><td class="column-2">DAESUNG HOLDINGS</td><td class="column-3">016710</td>
</tr>, <tr class="row-124 even">
<td class="column-1">123</td><td class="column-2">DAESUNGENERGY</td><td class="column-3">117580</td>
</tr>, <tr class="row-125 odd">
<td class="column-1">124</td><td class="column-2">DAESUNGIND</td><td class="column-3">128820</td>
</tr>, <tr class="row-126 even">
<td class="column-1">125</td><td class="column-2">DaewonCbl</td><td class="column-3">006340</td>
</tr>, <tr class="row-127 odd">
<td class="column-1">126</td><td class="column-2">DaewonCbl(1P)</td><td class="column-3">006345</td>
</tr>, <tr class="row-128 even">
<td class="column-1">127</td><td class="column-2">DaewonChem</td><td class="column-3">024890</td>
</tr>, <tr class="row-129 odd">
<td class="column-1">128</td><td class="column-2">DaewonKangup</td><td class="column-3">000430</td>
</tr>, <tr class="row-130 even">
<td class="column-1">129</td><td class="column-2">Daewonpharm</td><td class="column-3">003220</td>
</tr>, <tr class="row-131 odd">
<td class="column-1">130</td><td class="column-2">DAEWOOELECCOMPONENTS</td><td class="column-3">009320</td>
</tr>, <tr class="row-132 even">
<td class="column-1">131</td><td class="column-2">Daewoong</td><td class="column-3">003090</td>
</tr>, <tr class="row-133 odd">
<td class="column-1">132</td><td class="column-2">DAEWOONG PHARM</td><td class="column-3">069620</td>
</tr>, <tr class="row-134 even">
<td class="column-1">133</td><td class="column-2">DaeyoungPkg</td><td class="column-3">014160</td>
</tr>, <tr class="row-135 odd">
<td class="column-1">134</td><td class="column-2">DAIDONG</td><td class="column-3">008110</td>
</tr>, <tr class="row-136 even">
<td class="column-1">135</td><td class="column-2">DaishinSecu</td><td class="column-3">003540</td>
</tr>, <tr class="row-137 odd">
<td class="column-1">136</td><td class="column-2">DaishinSecu(1P)</td><td class="column-3">003545</td>
</tr>, <tr class="row-138 even">
<td class="column-1">137</td><td class="column-2">DAISHINSECU(2PB)</td><td class="column-3">003547</td>
</tr>, <tr class="row-139 odd">
<td class="column-1">138</td><td class="column-2">DaiyangMtl</td><td class="column-3">009190</td>
</tr>, <tr class="row-140 even">
<td class="column-1">139</td><td class="column-2">DaouTech</td><td class="column-3">023590</td>
</tr>, <tr class="row-141 odd">
<td class="column-1">140</td><td class="column-2">DASCO</td><td class="column-3">058730</td>
</tr>, <tr class="row-142 even">
<td class="column-1">141</td><td class="column-2">DAYOU A-TECH</td><td class="column-3">002880</td>
</tr>, <tr class="row-143 odd">
<td class="column-1">142</td><td class="column-2">DAYOUPLUS</td><td class="column-3">000300</td>
</tr>, <tr class="row-144 even">
<td class="column-1">143</td><td class="column-2">DB</td><td class="column-3">012030</td>
</tr>, <tr class="row-145 odd">
<td class="column-1">144</td><td class="column-2">DB HiTek</td><td class="column-3">000990</td>
</tr>, <tr class="row-146 even">
<td class="column-1">145</td><td class="column-2">DB HiTek(1P)</td><td class="column-3">000995</td>
</tr>, <tr class="row-147 odd">
<td class="column-1">146</td><td class="column-2">DB INSURANCE</td><td class="column-3">005830</td>
</tr>, <tr class="row-148 even">
<td class="column-1">147</td><td class="column-2">DBFI</td><td class="column-3">016610</td>
</tr>, <tr class="row-149 odd">
<td class="column-1">148</td><td class="column-2">DCM</td><td class="column-3">024090</td>
</tr>, <tr class="row-150 even">
<td class="column-1">149</td><td class="column-2">DENTIUM</td><td class="column-3">145720</td>
</tr>, <tr class="row-151 odd">
<td class="column-1">150</td><td class="column-2">DGB Financial Group</td><td class="column-3">139130</td>
</tr>, <tr class="row-152 even">
<td class="column-1">151</td><td class="column-2">DHICO</td><td class="column-3">034020</td>
</tr>, <tr class="row-153 odd">
<td class="column-1">152</td><td class="column-2">DI</td><td class="column-3">003160</td>
</tr>, <tr class="row-154 even">
<td class="column-1">153</td><td class="column-2">DIC</td><td class="column-3">004890</td>
</tr>, <tr class="row-155 odd">

In [6]:
#making columns and assigning values to the corresponding colunm
S_NO=[]
Name=[]
Code=[]
rows=table.findAll('tr')

for row in rows:
    cells=row.findAll('td')
    if(len(cells)==3):
        S_NO.append(cells[0].find(text=True))
        Name.append(cells[1].find(text=True))
        Code.append(cells[2].find(text=True))

In [7]:
Name

['A REIT',
 'A&P',
 'ABLE C&C',
 'AEKYUNG INDUSTRIAL',
 'AJ Networks',
 'AJ RENT A CAR',
 'AJU CAPITAL',
 'AK Holdings',
 'AK Petrochemical',
 'ALUKO',
 'ALVOGEN KOREA',
 'AmoreG',
 'AmoreG(1P)',
 'AMOREPACIFIC',
 'AMOREPACIFIC(1P)',
 'AnamElec',
 'Aprogen KIC',
 'Aprogen pharmaceuticals',
 'ARTIS',
 'ASIA HOLDINGS',
 'ASIACEMENT',
 'Asiana Airlines',
 'AsiaPaprMfg',
 'AUK',
 'Badaro19',
 'BaekkwangMinPdt',
 'Baiksan',
 'BGF',
 'BGF Retail',
 'Binggrae',
 'BNK Financial Group',
 'BohaeBrew',
 'Bolak',
 'Bookook Steel',
 'BookookSecu',
 'BookookSecu(1P)',
 'BoryungPharm',
 'BukwangPharm',
 'BUMYANG CONST',
 'BusanCtyGas',
 'BusanInd',
 'BYC',
 'BYC(1P)',
 'Byuksan',
 'CAMUS E&S',
 'CAPRO',
 'Celltrion',
 'Century',
 'Charm Engineering',
 'CHASYS',
 'CHEILGRINDING',
 'CheilWorldwide',
 'CHINHUNG INT (2PB)',
 'CHINHUNG INT(1PB)',
 'ChinhungInt',
 'Chinyang Holdings',
 'Chinyang Industry',
 'ChinYangChem',
 'ChinYangPoly',
 'Chobi',
 'CHOHEUNG',
 'CHOILALUMINUM',
 'ChokwangLeat',
 'ChokwangPaint',
 'Chonbang',
 'CHONGKUNDANG',
 'CHONGKUNDANG HOLDINGS',
 'CHOSUN WELDING',
 'ChosunRefrctr',
 'CHUNGHO',
 'ChunilExp',
 'CITECH',
 'CJ',
 'CJ CGV',
 'CJ CheilJedang',
 'CJ CheilJedang(1P)',
 'CJ Hello',
 'CJ LOGISTICS',
 'CJ(1P)',
 'CJSEAFOOD',
 'CJSEAFOOD(1P)',
 'CKDBio',
 'Comtec',
 'CONBUZZ',
 'COSMAX',
 'COSMAX bti',
 'CosmoAM&T',
 'COSMOCHEM',
 'COWAY',
 'CROWN',
 'CROWN(1P)',
 'CROWNHAITAI Holdings',
 'CROWNHAITAI Holdings(1P)',
 'CSHOLDINGS',
 'CSWIND',
 'CUCKOO',
 'CUCKOO HOMESYS',
 'CURO',
 'DAECHANG',
 'DaechangForging',
 'Daedong',
 'DAEDUCK(1P)',
 'DaeduckElec',
 'DAEDUCKGDS',
 'DaeguDptStr',
 'Daehan Steel',
 'DaehanFlrMill',
 'DaehanSynthFibr',
 'DAEHOAL',
 'Daehyun',
 'DAEKYO',
 'DAEKYO(1PB)',
 'DAELIM B&Co',
 'DAELIM C&S',
 'DaelimInd',
 'DaelimInd(1P)',
 'DaelimTrdg',
 'Daesang',
 'Daesang Holdings',
 'Daesang Holdings(1P)',
 'Daesang(1P)',
 'DAESUNG HOLDINGS',
 'DAESUNGENERGY',
 'DAESUNGIND',
 'DaewonCbl',
 'DaewonCbl(1P)',
 'DaewonChem',
 'DaewonKangup',
 'Daewonpharm',
 'DAEWOOELECCOMPONENTS',
 'Daewoong',
 'DAEWOONG PHARM',
 'DaeyoungPkg',
 'DAIDONG',
 'DaishinSecu',
 'DaishinSecu(1P)',
 'DAISHINSECU(2PB)',
 'DaiyangMtl',
 'DaouTech',
 'DASCO',
 'DAYOU A-TECH',
 'DAYOUPLUS',
 'DB',
 'DB HiTek',
 'DB HiTek(1P)',
 'DB INSURANCE',
 'DBFI',
 'DCM',
 'DENTIUM',
 'DGB Financial Group',
 'DHICO',
 'DI',
 'DIC',
 'DIC',
 'DOHWA ENGINEERING',
 'Dong Ah E&C',
 'DONG AH TIRE',
 'DONG IL STEEL',
 'Donga Socio Holdings',
 'Donga ST',
 'DongbangAgro',
 'DongbangTrnspt&Log',
 'Dongbu Corporation',
 'DONGBU STL',
 'DONGBU STL(1P)',
 'Dongbu(1P)',
 'Dongbuka12',
 'Dongbuka13',
 'Dongil',
 'DongkookInd',
 'DongkukStlMill',
 'DONGNAMCHEMICAL',
 'DONGSUH',
 'DONGSUNG CORPORATION',
 'DongsungChem',
 'DongsungPharm',
 'DongwhaPharm',
 'Dongwon',
 'DONGWON METAL',
 'DongwonF&B',
 'DongwonFish',
 'DongwonInd',
 'DONGYANG EXPRESS',
 'DONGYANG PISTON',
 'DongyangStlPipe',
 'DOOSAN',
 'Doosan Bobcat',
 'Doosan Engine',
 'DOOSAN(1P)',
 'DOOSAN(2PB)',
 'Doosanenc',
 'DOUZONE BIZON',
 'DPC',
 'DRB Holding',
 'DRB Industrial',
 'DSINFRA',
 'DSME',
 'DSR',
 'DSRWIRE',
 'DTR AUTOMOTIVE',
 'DUAL',
 'DuckYangInd',
 'Duksung',
 'Duksung(1P)',
 'DWEC',
 'DWS',
 'DWS(1P)',
 'DY',
 'DY POWER',
 'E1',
 'EagonInd',
 'EID',
 'emart',
 'Enex',
 'e-STARCO',
 'EUGENEIS',
 'EUSU HOLDINGS',
 'E-WORLD',
 'F&F',
 'FARMSCO',
 'Feelux',
 'FILA KOREA',
 'FINEBESTEEL',
 'FIRSTEC',
 'FOOSUNG',
 'Fursys',
 'GⅡR',
 'GALAXIA SM',
 'GAONCABLE',
 'GC Corp',
 'GCH Corp',
 'GCH Corp(2PB)',
 'GENEONE',
 'GKL',
 'GMB Korea',
 'GOLDENBRIDGEINV&SEC',
 'GREEN CHEMICAL',
 'GS',
 'GS E&C',
 'GS Global',
 'GS Retail',
 'GS(1P)',
 'Gwangju Shinsegae',
 'H.I.S.C',
 'H.I.S.C(1P)',
 'H.S.ENTERPRISE',
 'HaeinCorp',
 'HAESUNG DS',
 'Haitai Confectionery',
 'Halla',
 'HALLA HOLDINGS',
 'HANA NICKEL 1',
 'HANA NICKEL 2',
 'HANAFINANCIALGR',
 'HANALL BIOPHARMA',
 'HANATOUR SERVICE',
 'Hanchang',
 'HanchangPaper',
 'Hanchem',
 'HANDOK',
 'HANDS CORPORATION',
 'Handsome',
 'HanExpress',
 'HanilCement',
 'HanilIron&Stl',
 'HANJIN HVY IND',
 'HANJINKAL',
 'HANJINKAL(1P)',
 'HanjinTrnspt',
 'HANKOOK TIRE',
 'HANKOOK TIRE WORLDWIDE',
 'HANKOOKCOSMETICS',
 'HankookShellOil',
 'HankookSteel',
 'HankukCarbon',
 'HankukGlas',
 'HankukGlas(1P)',
 'HankukPaprMfg',
 'Hanmi Science',
 'HanmiGlobal',
 'HanmiPharm',
 'HANMISemi',
 'HANNONG',
 'Hanon Systems',
 'Hansae',
 'HANSAEMK',
 'HansaeYes24Holdings',
 'HanshinConst',
 'HanshinMach',
 'HANSOL HOLDINGS',
 'Hansol Logistics',
 'HANSOLPAPER',
 'HANSOLPNS',
 'HansolTechnics',
 'Hanssem',
 'HansungEnt',
 'Hanwha',
 'HANWHA AEROSPACE',
 'Hanwha General Ins',
 'HANWHA LIFE',
 'Hanwha(1P)',
 'HANWHA(3PB)',
 'HanwhaChem',
 'HanwhaChem(1P)',
 'HanyangSecu',
 'HanyangSecu(1P)',
 'HDC I-CONTROLS',
 'HDCHEP',
 'HeungaShipping',
 'HeungkukF&MIns',
 'HeungkukF&MIns(1P)',
 'HeungkukF&MIns(2PB)',
 'HGTC',
 'HHI',
 'HHICHoldings',
 'Hi Gold No.12',
 'Hi Gold No.3',
 'Hi Gold No.8',
 'HISTEEL',
 'HITEJINRO',
 'HITEJINRO(2PB)',
 'HITEJINROHOLDINGS',
 'HITEJINROHOLDINGS(1P)',
 'Hitron',
 'HKCManufacture',
 'HMCIB',
 'HMT',
 'Hojeon',
 'HomeDeco',
 'HS R&A',
 'HSInd',
 'HtlShilla',
 'HtlShilla(1P)',
 'Huchems',
 'HuneedTechnologies',
 'HUSTEEL',
 'HUVIS',
 'HWACHEON',
 'HwangKum S&T',
 'Hwashin',
 'HwasungInd',
 'Hyosung',
 'HYOSUNG ITX',
 'HYUNDAI BNG STEEL',
 'HYUNDAI BNG STEEL(1P)',
 'HYUNDAI CE',
 'HYUNDAI CORPORATION HOLDINGS',
 'Hyundai Dvp Co',
 'HYUNDAI ELECTRIC',
 'Hyundai HCN',
 'HYUNDAI HEAVY INDUSTRIES HOLDINGS',
 'Hyundai M&F INS',
 'Hyundai pharm',
 'HYUNDAI ROTEM',
 'HYUNDAI STEEL',
 'HYUNDAI WIA',
 'HyundaiCement',
 'HyundaiCorp',
 'HYUNDAIDEPTST',
 'HyundaiElev',
 'HyundaiEng&Con(1P)',
 'HyundaiEng&Const',
 'HYUNDAIGLOVIS',
 'HYUNDAIGREENFOOD',
 'HYUNDAIHOMESHOP',
 'HYUNDAILIVART',
 'HyundaiMercMar',
 'HyundaiMipoDock',
 'HyundaiMtr',
 'HyundaiMtr(1P)',
 'HyundaiMtr(2PB)',
 'HyundaiMtr(3PB)',
 'HYUNGJI ELITE',
 'IBK',
 'IHQ',
 'ILDONG HOLDINGS',
 'ILDONG PHARM',
 'IljeongInd',
 'ILJIN DIAMOND',
 'ILJIN ELECTRIC',
 'ILJIN MATERIALS',
 'ILJINDISPLAY',
 'ILJINHOLDINGS',
 'IlshinSpng',
 'IlshinStone',
 'IlsungConst',
 'IlsungPharm',
 'IlyangPharm',
 'IlyangPharm(1P)',
 'iMarketKorea',
 'In the F',
 'INCHEON CITY GAS',
 'INFAC',
 'ING Life Korea',
 'INNOCEAN',
 'INSCOB',
 'INTERGIS',
 'Inzi',
 'IS DONGSEO',
 'IsuChem',
 'ISUPETASYS',
 'ITSHANBUL',
 'JahwaElec',
 'Jayjun Cosmetic',
 'JB Financial Group',
 'JEIL PHARM',
 'JEIL PHARMA HOLDINGS',
 'Jeju BK',
 'JEJUAIR',
 'JICO',
 'JIN AIR',
 'JINDO',
 'JOOYONTECH',
 'JS CORP',
 'JW HOLDINGS',
 'JW LIFESCIENCE',
 'JWPHARMA',
 'JWPHARMA(1P)',
 'JWPHARMA(2PB)',
 'KAIT',
 'Kakao',
 'KAL',
 'KAL(1P)',
 'KANGNAM JEVISCO',
 'Kangwonland',
 'KBFinancialGroup',
 'KC',
 'KC COTTRELL',
 'KC Green Holdings',
 'KCC',
 'KCTC',
 'KCTECH',
 'KDHC',
 'KEC',
 'KECC',
 'KECHOLDINGS',
 'KEPCO',
 'KEPCO E&C',
 'KEPCO KPS',
 'KEPID',
 'KeyangElecMach',
 'KeyangElecMach(1P)',
 'KGC',
 'KiaMtr',
 'KidariStudio',
 'KIH',
 'KIH(1P)',
 'KIM ANKOR OIL',
 'KIM Parallel OIL',
 'KISCO',
 'KISCO Holdings',
 'KISHIN',
 'KISWire',
 'Kiwi Media Group',
 'KIWOOM',
 'KleanNara',
 'KleanNara(1P)',
 'KOAS',
 'Kogas',
 'KOLON CORP',
 'KOLON CORP(1P)',
 'KOLON IND',
 'KOLON IND(1P)',
 'KOLON PLASTICS',
 'KolonGlobal',
 'KolonGlobal(1P)',
 'KolonMaterial',
 'KOR CIRC(2PB)',
 'KorApoSvc',
 'KorCastIronPipe',
 'KorCirc',
 'KorCirc(1P)',
 'KorDev',
 'KOREA AEROSPACE',
 'KOREA AUTOGLASS',
 'KOREA KOLMAR',
 'KOREA KOLMAR HOLDINGS',
 'Korean Re',
 'KOREIT',
 'KorElecTerm',
 'KorExptPkgInd',
 'KorFlange',
 'KorInd',
 'KorLine',
 'KorPetro',
 'KorZinc',
 'KOSCO',
 'KPIC',
 'KPXCHEMICAL',
 'KPXHOLDINGS',
 'KR MOTORS',
 'Krc',
 'KSS LINE',
 'KT',
 'KT Skylife',
 'KT&G',
 'KTBSEC',
 'KTcs',
 'ktis',
 'KTOPREITs',
 'KukboTrnspt',
 'KukdoChem',
 'Kukdong',
 'KukdongOil&Chem.',
 'Kukje Pharma',
 'Kumbi',
 'KUMHO HT',
 'KumhoElec',
 'KumhoIndustrial',
 'KumhoIndustrial(1P)',
 'KumhoPetrochem',
 'KumhoPetrochem(1P)',
 'KUMHOTIRE',
 'KUMKANG KIND',
 'KUMKANG KIND(1P)',
 'Kumyang',
 'KUP',
 'KWANG MYUNG ELEC',
 'KwangdongPharm',
 'Kwangju Bank',
 'KyeryongConst',
 'KYOBOSECURITIES',
 'KYONGBO',
 'Kyungbang',
 'KYUNGDONG CITY GAS',
 'KYUNGDONG INVEST',
 'KYUNGDONGNAVIEN',
 'KyunginElec',
 'KyunginSynth',
 'Kyungnong',
 'L&L',
 'LeekuInd',
 'LF',
 'LG Corp.',
 'LG Corp.(1P)',
 'LG Display',
 'LG HAUSYS',
 'LG HAUSYS(1P)',
 'LG Innotek',
 'LG Uplus',
 'LGCHEM',
 'LGCHEM(1P)',
 'LGELECTRONICS',
 'LGELECTRONICS(1P)',
 'LGH&H',
 'LGH&H(1P)',
 'LGInt',
 'LIG Nex1',
 'LOTTE',
 'LOTTE CHEMICAL Corp',
 'LOTTE CONF',
 'LOTTE Fine Chem',
 'LOTTE Himart',
 'LOTTE SHOPPING',
 'LOTTE TOUR',
 'LOTTE(1P)',
 'LotteChilsung',
 'LotteChilsung(1P)',
 'LotteFood',
 'LotteInsurance',
 'LS',
 'LS C&S ASIA',
 'LSINDUSTRIALSYSTEMS',
 'LSNetworks',
 'LVMC Holdings',
 'MANDO',
 'ManhoRope&Wire',
 'MANIKER',
 'MAPSREALTY1',
 'MCC',
 'Mediplant',
 'Meritz Financial',
 'Meritz Insurance',
 'MERITZ SECU',
 'METALABS',
 'MHETHANOL',
 'MichangOil',
 'Mirae',
 'MIRAE ASSET DAEWOO',
 'MIRAE ASSET DAEWOO(1P)',
 'MIRAE ASSET DAEWOO(2PB)',
 'MIRAE ASSET LIFE',
 'MiraeING',
 'MIWON SC',
 'MiwonComcl',
 'MKIF',
 'Mobis',
 'MODETOURREIT',
 'Monalisa',
 'Monami',
 'MoonbaeStl',
 'Moorim P&P',
 'MOORIM PAPER',
 'MT',
 'Muhak',
 'MWH',
 'Myungmoon Pharm',
 'NamhaeChem',
 'NamkwangEng&Const',
 'NamsunAlum',
 'NamsunAlum(1P)',
 'Namsung',
 'NamyangDairy',
 'NamyangDairy(1P)',
 'NAMYEUNG',
 'NANOMEDICS',
 'NAVER',
 'NCsoft',
 'Netmarble',
 'NEXEN',
 'NEXEN(1P)',
 'NEXENTIRE',
 'NEXENTIRE(1PB)',
 'NHIS',
 'NHIS(1P)',
 'NHN Entertainment',
 'NI STEEL',
 'NICE',
 'NK',
 'NK MULSAN',
 'Nongshim',
 'NongshimHoldings',
 'NorooHoldings',
 'NorooHoldings(1P)',
 'NOROOPAINT',
 'NOROOPAINT(1P)',
 'NPC',
 'NPC(1P)',
 'NS Shopping',
 'OBI',
 'OCI',
 'ORION',
 'ORION Holdings',
 'Ottogi',
 'OYANG',
 'PaikkwangInd',
 'Pangrim',
 'PanOcean',
 'PAN-PACIFIC',
 'PaperCorea',
 'Pharmicell',
 'PHC',
 'PHHC',
 'PMO',
 'POLUS BioPharm',
 'POONGSAN',
 'POONGSAN HOLDINGS',
 'POSCO',
 'POSCO C&C',
 'POSCO DAEWOO',
 'PusanCstIron',
 'REYON',
 'RIFA',
 'S&T',
 'S&T Holdings',
 'S&T MOTIV',
 'S&TDynamics',
 'S-1',
 'SAC',
 'SAEHWA IMC',
 'SAH',
 'SAJODONGAONE',
 'SajoInd',
 'SAJOSEAFOOD',
 'SamaAlum',
 'SambuConst',
 'Samchully',
 'SamhoInt',
 'SamhwaCrown&Closure',
 'SamhwaPaint',
 'SamickMusInstr',
 'SAMICKTHK',
 'SamilPharm',
 'SamjinPharm',
 'SAMJUNGPULP',
 'SAMKWANG GLASS',
 'SAMSUNG BIOLOGICS',
 'SAMSUNG C&T',
 'SAMSUNG C&T(1PB)',
 'SAMSUNG CARD',
 'SAMSUNG LIFE',
 'SAMSUNG PHARM',
 'SAMSUNG PUBLISHING',
 'SAMSUNG SDI CO.,LTD.',
 'SAMSUNG SDI(1P)',
 'SAMSUNG SDS',
 'SamsungClimateContro',
 'SamsungElec',
 'SamsungElec(1P)',
 'SamsungElecMech',
 'SamsungElecMech(1P)',
 'SamsungEng',
 'SamsungF&MIns',
 'SamsungF&MIns(1P)',
 'SamsungHvyInd',
 'SamsungHvyInd(1P)',
 'SamsungSecu',
 'SamwhaCapacitor',
 'SamwhaElec',
 'SamwhaElec',
 'SAMWONSTEEL',
 'SAMYANG PACKAGING',
 'SamyangFood',
 'SAMYANGHOLDINGS',
 'SAMYANGHOLDINGS(1P)',
 'SamyangTongsang',
 'SamyoungChem',
 'SamyoungElec',
 'SamyungTrdg',
 'SANGSIN',
 'SAVEZONEI&C',
 'SBC',
 'SBS',
 'SBS Media Holdings',
 'SBW',
 'SC ENGINEERING',
 'SCEHoldings',
 'SDC',
 'SeAH SPECIAL STEEL',
 'SeAhStl',
 'SEBANG',
 'SEBANG(1P)',
 'seha',
 'SEJIN HEAVY',
 'SEJONG',
 'SEMPIO',
 'SEMPIO FOODS',
 'SeondoElec',
 'Seongan',
 'SeoulCtyGas',
 'SeoulFoodInd',
 'SeoulFoodInd(1P)',
 'Seowon',
 'SEOYON',
 'SEOYONEHWA',
 'SEWON CELLONTECH',
 'SewonPrecsnInd',
 'Sewooglobal',
 'SF',
 'SG CHOONGBANG',
 'SGBC',
 'SGCORPORATION',
 'SH ENERCHEM',
 'ShindaeyangPapr',
 'ShinhanEng&Const',
 'ShinhanGroup',
 'Shinhung',
 'ShinhwaSilup',
 'ShinilInd',
 'ShinpoongPaprMfg',
 'ShinpoongPharm',
 'ShinpoongPharm(1P)',
 'Shinsegae',
 'SHINSEGAE I&C',
 'SHINSEGAE INTERNATIONAL',
 'ShinsegaeE&C',
 'SHINSUNG E&G',
 'ShinsungTongsang',
 'Shinwon',
 'Shinwon(1P)',
 'ShinyoungSecu',
 'ShinyoungSecu(1P)',
 'ShinyoungWacoal',
 'Sidiz',
 'Silla',
 'SIMPAC',
 'SINDOH',
 'SINGSONGHOLDINGS',
 'SJ HP',
 'SJDR',
 'SJM',
 'SJMH',
 'SK',
 'SK Discovery',
 'SK Discovery(1P)',
 'SK hynix',
 'SK Innovation',
 'SK Innovation(1P)',
 'SK(1P)',
 'SKC',
 'SKCHEM',
 'SKCHEM(1P)',
 'SKD&D',
 'SKGas',
 'SKNetworks',
 'SKNetworks(1P)',
 'SKSecu',
 'SKSecu(1P)',
 'SKTelecom',
 'SLCORP',
 'S-Oil',
 'S-Oil(1P)',
 'SongwonInd',
 'SoosanHvyInd',
 'SPC SAMLIP',
 'SsangyongCement',
 'SsangyongCement(1P)',
 'SsangyongMtr',
 'STX',
 'STX Heavy Industries',
 'STXEngine',
 'SUHEUNG',
 'Sunchang',
 'SungboChem',
 'SungjeeConst',
 'SungmoonElec',
 'SungmoonElec(1P)',
 'SungshinCement',
 'SungshinCement(1P)',
 'SungshinCement(2PB)',
 'SungshinCement(3PB)',
 'SUNJIN',
 'SunnyElec',
 'SYC',
 'SYC(1P)',
 'TaekwangInd',
 'TAEKYUNGCHEMICAL',
 'TaekyungInd',
 'TaewonMulsan',
 'TaeyangMtl',
 'TaeyangMtl(1P)',
 'TAEYOUNG E&C',
 'TAEYOUNG E&C(1P)',
 'TaihanElecWire',
 'TaihanTextl',
 'Tailim Pkg',
 'TAPEX',
 'TBH GLOBAL',
 'TCC STEEL',
 'TELCOWARE',
 'THN',
 'TONGYANG',
 'TONGYANG LIFE',
 'TONGYANG(1P)',
 'TONGYANG(2PB)',
 'TONGYANG(3PB)',
 'TongyangMoolsan',
 'TONYMOLY',
 'TRUS Y 7 REIT',
 'TS',
 'TS(1P)',
 'TS(3PB)',
 "T'way Holdings",
 'TYNETWORKS',
 'UANGEL',
 'UNI CHEM',
 'UNID',
 'Union',
 'UNIONMaterials',
 'Uniquest',
 'VIETNAM DEVELOP1',
 'VISANG',
 'WELLBIOTEC',
 'WhaninPharm',
 'WIB',
 'WillBes',
 'WISCOM',
 'Wonlim',
 'WOOJIN',
 'WOOJIN PLAIMM',
 'WOONGJIN',
 'WOONGJIN THINKBIG',
 'WoongjinEnergy',
 'Woori Bank',
 'WOORIDUL HUEBRAIN',
 'WOORIDUL PHARM',
 'WooshinSystems',
 'WoosungFeed',
 'YeonghwaMtl',
 'Yesco Holdings',
 'YGP',
 'YoosungEnt',
 'YoulchonChem',
 'YOUNG HEUNG I&S',
 'YoungboChem',
 'Youngone Corp',
 'YoungoneHoldings',
 'Youngpoong',
 'YoungpoongPaprMfg',
 'YP',
 'Yuanta Securities',
 'Yuanta Securities(1P)',
 'Yuhan',
 'Yuhan(1P)',
 'YuhwaSecu',
 'YuhwaSecu(1P)',
 'YUNGJIN PHARM',
 'YUYANG D&U',
 'YuyuPharma',
 'YuyuPharma(1P)',
 'YuyuPharma(2PB)']

In [8]:
#creating df1
df1 = pd.DataFrame()
df1['S_NO']=S_NO
df1['Name']=Name
df1['Code']=Code

df1

    S_NO                Name    Code
0      1              A REIT  140910
1      2                 A&P  015260
2      3            ABLE C&C  078520
3      4  AEKYUNG INDUSTRIAL  018250
4      5         AJ Networks  095570
..   ...                 ...     ...
886  887       YUNGJIN PHARM  003520
887  888          YUYANG D&U  011690
888  889          YuyuPharma  000220
889  890      YuyuPharma(1P)  000225
890  891     YuyuPharma(2PB)  000227

[891 rows x 3 columns]

In [16]:
#adding ".KS" to the stock code since thats how yfinance read Korean stock
df1['Code']=df1['Code']+'.KS'

In [17]:
df1

    S_NO                Name       Code
0      1              A REIT  140910.KS
1      2                 A&P  015260.KS
2      3            ABLE C&C  078520.KS
3      4  AEKYUNG INDUSTRIAL  018250.KS
4      5         AJ Networks  095570.KS
..   ...                 ...        ...
886  887       YUNGJIN PHARM  003520.KS
887  888          YUYANG D&U  011690.KS
888  889          YuyuPharma  000220.KS
889  890      YuyuPharma(1P)  000225.KS
890  891     YuyuPharma(2PB)  000227.KS

[891 rows x 3 columns]

In [9]:
pip install yfinance

Requirement already satisfied: yfinance in /Users/bellacho/opt/anaconda3/lib/python3.7/site-packages (0.1.55)
Requirement already satisfied: pandas>=0.24 in /Users/bellacho/opt/anaconda3/lib/python3.7/site-packages (from yfinance) (1.0.1)
Requirement already satisfied: multitasking>=0.0.7 in /Users/bellacho/opt/anaconda3/lib/python3.7/site-packages (from yfinance) (0.0.9)
Requirement already satisfied: numpy>=1.15 in /Users/bellacho/opt/anaconda3/lib/python3.7/site-packages (from yfinance) (1.18.1)
Requirement already satisfied: requests>=2.20 in /Users/bellacho/opt/anaconda3/lib/python3.7/site-packages (from yfinance) (2.22.0)
Requirement already satisfied: lxml>=4.5.1 in /Users/bellacho/opt/anaconda3/lib/python3.7/site-packages (from yfinance) (4.6.2)
Requirement already satisfied: pytz>=2017.2 in /Users/bellacho/opt/anaconda3/lib/python3.7/site-packages (from pandas>=0.24->yfinance) (2019.3)
Requirement already satisfied: python-dateutil>=2.6.1 in /Users/bellacho/opt/anaconda3/lib/python3.7/site-packages (from pandas>=0.24->yfinance) (2.8.1)
Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in /Users/bellacho/opt/anaconda3/lib/python3.7/site-packages (from requests>=2.20->yfinance) (1.25.8)
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in /Users/bellacho/opt/anaconda3/lib/python3.7/site-packages (from requests>=2.20->yfinance) (3.0.4)
Requirement already satisfied: idna<2.9,>=2.5 in /Users/bellacho/opt/anaconda3/lib/python3.7/site-packages (from requests>=2.20->yfinance) (2.8)
Requirement already satisfied: certifi>=2017.4.17 in /Users/bellacho/opt/anaconda3/lib/python3.7/site-packages (from requests>=2.20->yfinance) (2019.11.28)
Requirement already satisfied: six>=1.5 in /Users/bellacho/opt/anaconda3/lib/python3.7/site-packages (from python-dateutil>=2.6.1->pandas>=0.24->yfinance) (1.14.0)
Note: you may need to restart the kernel to use updated packages.

In [10]:
import yfinance as yf
from datetime import datetime, date, timedelta
import time

In [14]:
a=yf.Ticker('140910.KS')
a.info

{'sector': 'Real Estate',
 'longBusinessSummary': 'Kwanghee Development-oriented Self-administered REIT Inc. is based in South Korea.',
 'city': 'Seoul',
 'phone': '82 2 2077 5800',
 'country': 'South Korea',
 'companyOfficers': [],
 'website': 'http://www.khreit.com',
 'maxAge': 1,
 'address1': 'Seoul Metropolitan City',
 'industry': 'REIT—Residential',
 'address2': '9th floor Kangnam Ku Eonjuro 711',
 'previousClose': 8220,
 'regularMarketOpen': 8220,
 'twoHundredDayAverage': 7148.0283,
 'trailingAnnualDividendYield': None,
 'payoutRatio': 0.23570000000000002,
 'volume24Hr': None,
 'regularMarketDayHigh': 8250,
 'navPrice': None,
 'averageDailyVolume10Day': 15775,
 'totalAssets': None,
 'regularMarketPreviousClose': 8220,
 'fiftyDayAverage': 8318.333,
 'trailingAnnualDividendRate': None,
 'open': 8220,
 'toCurrency': None,
 'averageVolume10days': 15775,
 'expireDate': None,
 'yield': None,
 'algorithm': None,
 'dividendRate': 414.81,
 'exDividendDate': 1577404800,
 'beta': None,
 'circulatingSupply': None,
 'startDate': None,
 'regularMarketDayLow': 8000,
 'priceHint': 2,
 'currency': 'KRW',
 'regularMarketVolume': 16038,
 'lastMarket': None,
 'maxSupply': None,
 'openInterest': None,
 'marketCap': 31087921152,
 'volumeAllCurrencies': None,
 'strikePrice': None,
 'averageVolume': 40830,
 'priceToSalesTrailing12Months': 0.69941545,
 'dayLow': 8000,
 'ask': 8260,
 'ytdReturn': None,
 'askSize': None,
 'volume': 16038,
 'fiftyTwoWeekHigh': 9690,
 'forwardPE': None,
 'fromCurrency': None,
 'fiveYearAvgDividendYield': 8.24,
 'fiftyTwoWeekLow': 5010,
 'bid': 8200,
 'tradeable': False,
 'dividendYield': 0.0505,
 'bidSize': None,
 'dayHigh': 8250,
 'exchange': 'KSC',
 'shortName': 'A REIT',
 'longName': 'A Self-Administered Real Estate Investment Trust Inc.',
 'exchangeTimezoneName': 'Asia/Seoul',
 'exchangeTimezoneShortName': 'KST',
 'isEsgPopulated': False,
 'gmtOffSetMilliseconds': '32400000',
 'quoteType': 'EQUITY',
 'symbol': '140910.KS',
 'messageBoardId': 'finmb_130911335',
 'market': 'kr_market',
 'annualHoldingsTurnover': None,
 'enterpriseToRevenue': 1.434,
 'beta3Year': None,
 'profitMargins': 0.017570000000000002,
 'enterpriseToEbitda': 71.096,
 '52WeekChange': 0.16219246,
 'morningStarRiskRating': None,
 'forwardEps': None,
 'revenueQuarterlyGrowth': None,
 'sharesOutstanding': 3791210,
 'fundInceptionDate': None,
 'annualReportExpenseRatio': None,
 'bookValue': None,
 'sharesShort': None,
 'sharesPercentSharesOut': None,
 'fundFamily': None,
 'lastFiscalYearEnd': None,
 'heldPercentInstitutions': 0,
 'netIncomeToCommon': 781158208,
 'trailingEps': None,
 'lastDividendValue': None,
 'SandP52WeekChange': 0.14789832,
 'priceToBook': None,
 'heldPercentInsiders': 0.48424998,
 'nextFiscalYearEnd': None,
 'mostRecentQuarter': 1380499200,
 'shortRatio': None,
 'sharesShortPreviousMonthDate': None,
 'floatShares': None,
 'enterpriseValue': 63725473792,
 'threeYearAverageReturn': None,
 'lastSplitDate': None,
 'lastSplitFactor': None,
 'legalType': None,
 'lastDividendDate': None,
 'morningStarOverallRating': None,
 'earningsQuarterlyGrowth': None,
 'dateShortInterest': None,
 'pegRatio': None,
 'lastCapGain': None,
 'shortPercentOfFloat': None,
 'sharesShortPriorMonth': None,
 'impliedSharesOutstanding': None,
 'category': None,
 'fiveYearAverageReturn': None,
 'regularMarketPrice': 8220,
 'logo_url': 'https://logo.clearbit.com/khreit.com'}

In [18]:
a.recommendations

In [20]:
a.actions

Empty DataFrame
Columns: [Dividends, Stock Splits]
Index: []